In [61]:
import pandas as pd
import matplotlib as plt
import numpy as np

In [78]:
data = pd.read_csv("Student_Performance.csv")
print(data)
data['Extracurricular Activities'] = data['Extracurricular Activities'].map({'Yes': 1, 'No' : 0})

      Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced 

In [79]:
print(data.head)

<bound method NDFrame.head of       Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0                 7               99                           1            9   
1                 4               82                           0            4   
2                 8               51                           1            7   
3                 5               52                           1            5   
4                 7               75                           0            8   
...             ...              ...                         ...          ...   
9995              1               49                           1            4   
9996              7               64                           1            8   
9997              6               83                           1            8   
9998              9               97                           1            7   
9999              7               74                           0            8  

In [80]:
print(data.columns)

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')


In [81]:
df = pd.DataFrame(data)

In [82]:
#here performance index is the dependent data remaining are not so
x = df.drop(['Performance Index'],axis=1).values

In [83]:
print(x)

[[ 7 99  1  9  1]
 [ 4 82  0  4  2]
 [ 8 51  1  7  2]
 ...
 [ 6 83  1  8  5]
 [ 9 97  1  7  0]
 [ 7 74  0  8  1]]


In [84]:
y = df['Performance Index'].values

In [94]:
print(y)

[91. 65. 45. ... 74. 95. 64.]


In [95]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [96]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 0)

In [97]:
model = LinearRegression()

In [98]:
model.fit(x_train,y_train)

LinearRegression()

In [99]:
y_pred = model.predict(x_test)

In [100]:
print(y_pred)

[50.46443613 53.10077726 78.27207629 ... 61.92684246 39.15895897
 89.59303935]


In [92]:
print(y)

[91. 65. 45. ... 74. 95. 64.]


In [93]:
from sklearn.metrics import mean_squared_error, r2_score
mse_after = mean_squared_error(y_test, y_pred)
r2_after = r2_score(y_test, y_pred)
print(mse_after)
print(r2_after)

4.039519191698861
0.9888065859708454


In [103]:
model.score(x_train,y_train)

0.988725946864821

In [104]:
print(x)

[[ 7 99  1  9  1]
 [ 4 82  0  4  2]
 [ 8 51  1  7  2]
 ...
 [ 6 83  1  8  5]
 [ 9 97  1  7  0]
 [ 7 74  0  8  1]]


In [109]:
new_data = [[7,99,1,9,1]]

u = model.predict(new_data)

In [110]:
print(u)

[91.88368083]
